<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class productoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('productos')->insert([
            [
                'titulo' => 'Sudadera',
                'descripcion' => 'Es una prenda de ropa con un color azul oscuro',
                'tipo' => 'ropa',
                'categoria_prenda' => 'sudadera con capucha',
                'genero' => 'masculino',
                'marca' => 'nike',
                'precio' => 18.99,
                'valoracion' => 4,
                'imagen' => 'img/productos/1/sudadera1.jpg',
                'img2' => 'img/productos/1/sudadera2.jpg',
                'img3' => 'img/productos/1/sudadera3.jpg',
                'img4' => 'img/productos/1/sudadera4.jpg',
                'etiquetas' => 'oversize',
            ],
            [
                'titulo' => 'Pantalones',
                'descripcion' => 'Es una prenda de ropa con un color azul oscuro',
                'tipo' => 'ropa',
                'categoria_prenda' => 'pantalones',
                'genero' => 'masculino',
                'marca' => 'levis',
                'precio' => 25.99,
                'valoracion' => 3,
                'imagen' => 'img/productos/2/pantalon1.jpg',
                'img2' => 'img/productos/2/pantalon2.jpg',
                'img3' => 'img/productos/2/pantalon3.jpg',
                'img4' => 'img/productos/2/pantalon4.jpg',
                'etiquetas' => '',
            ],
            [
                'titulo' => 'anillo',
                'descripcion' => 'Es una prenda de ropa con un color azul oscuro',
                'tipo' => 'complementos',
                'categoria_prenda' => 'complementos',
                'genero' => 'femenino',
                'marca' => 'pandora',
                'precio' => 84.99,
                'valoracion' => 5,
                'imagen' => 'img/productos/3/anillo1.jpg',
                'img2' => 'img/productos/3/anillo2.jpg',
                'img3' => 'img/productos/3/anillo3.jpg',
                'img4' => 'img/productos/3/anillo4.jpg',
                'etiquetas' => 'anillo',
            ],
            [
                'titulo' => 'Nike air force 1',
                'descripcion' => 'Es una prenda de ropa con un color azul oscuro',
                'tipo' => 'calzado',
                'categoria_prenda' => 'zapatos',
                'genero' => 'unisex',
                'marca' => 'nike',
                'precio' => 100.99,
                'valoracion' => 5,
                'imagen' => 'img/productos/4/nike1.jpg',
                'img2' => 'img/productos/4/nike2.jpg',
                'img3' => 'img/productos/4/nike3.jpg',
                'img4' => 'img/productos/4/nike4.jpg',
                'etiquetas' => 'zapatos',
            ],
            [
                'titulo' => 'Pendientes',
                'descripcion' => 'Pendientes de oro',
                'tipo' => 'complementos',
                'categoria_prenda' => 'complemento',
                'genero' => 'femenino',
                'marca' => 'tous',
                'precio' => 180.99,
                'valoracion' => 4,
                'imagen' => 'img/productos/5/pendientes1.jpg',
                'img2' => 'img/productos/5/pendientes2.jpg',
                'img3' => 'img/productos/5/pendientes3.jpg',
                'img4' => 'img/productos/5/pendientes4.jpg',
                'etiquetas' => 'pendientes',
            ],
            [
                'titulo' => 'Adidas Forum Low',
                'descripcion' => 'Nuevas adidas formum en formato low color Blanco/azul',
                'tipo' => 'calzado',
                'categoria_prenda' => 'zapatos',
                'genero' => 'unisex',
                'marca' => 'adidas',
                'precio' => 99.99,
                'valoracion' => 5,
                'imagen' => 'img/productos/6/adidas1.jpg',
                'img2' => 'img/productos/6/adidas2.jpg',
                'img3' => 'img/productos/6/adidas3.jpg',
                'img4' => 'img/productos/6/adidas4.jpg',
                'etiquetas' => 'zapatos',
            ],
            [
                'titulo' => 'Vans Old Skool',
                'descripcion' => 'Las miticas zapatillas de skater vans en su version en negro',
                'tipo' => 'calzado',
                'categoria_prenda' => 'zapatos',
                'genero' => 'unisex',
                'marca' => 'vans',
                'precio' => 39.99,
                'valoracion' => 5,
                'imagen' => 'img/productos/7/vans1.jpg',
                'img2' => 'img/productos/7/vans2.jpg',
                'img3' => 'img/productos/7/vans3.jpg',
                'img4' => 'img/productos/7/vans4.jpg',
                'etiquetas' => 'zapatos',
            ],
            [
                'titulo' => 'Camiseta Tommy Hilfiger',
                'descripcion' => 'Camiseta basica de la marca Tommy Hilfiger',
                'tipo' => 'ropa',
                'categoria_prenda' => 'camiseta',
                'genero' => 'masculino',
                'marca' => 'Tommy Hilfiger',
                'precio' => 22.95,
                'valoracion' => 5,
                'imagen' => 'img/productos/8/camiseta1.jpg',
                'img2' => 'img/productos/8/camiseta2.jpg',
                'img3' => 'img/productos/8/camiseta3.jpg',
                'img4' => 'img/productos/8/camiseta4.jpg',
                'etiquetas' => 'camiseta',
            ],
            [
                'titulo' => 'Falda vaquera',
                'descripcion' => 'khgjhfjh',
                'tipo' => 'ropa',
                'categoria_prenda' => 'falda',
                'genero' => 'femenino',
                'marca' => 'Calvin klein',
                'precio' => 21.48,
                'valoracion' => 5,
                'imagen' => 'img/productos/9/falda1.jpg',
                'img2' => 'img/productos/9/falda2.jpg',
                'img3' => 'img/productos/9/falda3.jpg',
                'img4' => 'img/productos/9/falda4.jpg',
                'etiquetas' => 'falda',
            ],
            [
                'titulo' => 'Cazadora vaquera',
                'descripcion' => 'khgjhfjh',
                'tipo' => 'ropa',
                'categoria_prenda' => 'cazadora',
                'genero' => 'masculino',
                'marca' => 'Levis',
                'precio' => 90.00,
                'valoracion' => 5,
                'imagen' => 'img/productos/10/cazadora1.jpg',
                'img2' => 'img/productos/10/cazadora2.jpg',
                'img3' => 'img/productos/10/cazadora3.jpg',
                'img4' => 'img/productos/10/cazadora4.jpg',
                'etiquetas' => 'falda',
            ],

        ]);
    }
}